### ISSUE TITLE
can not find data/priors/unity_betas.npz 

### ISSUE THREAD

**Issue by zbxzc35** [chaneyddtt/Coarse-to-fine-3D-Animal#1]
Thanks for your excellent work! I'm trying to run the demo, but I got an error 'No such file or directory: 'data/priors/unity_betas.npz'. Will you upload this file later?

**Comment by zbxzc35** [comment]
I managed to find unity_betas.npz in this [repo](https://github.com/benjiebob/SMALify/tree/master/data/priors),and my_smpl_data_00781_4_all.pkl in this [repo](https://github.com/benjiebob/WLDO/tree/master/data/smal), but I still can not find where mesh_down_sampling_4.npz is. Need help.

**Comment by chaneyddtt** [comment]
Hi, I have updated the instruction, please refer to the 'Download SMAL and priors' section.

**Comment by chaneyddtt** [comment]
The mesh_down_sampling_4.npz file is also uploaded.

**Comment by zbxzc35** [comment]
> 

Thansk a lot!
