### ISSUE TITLE
How to retrieve the 3D mesh in a .ply or .obj format ? 

### ISSUE THREAD

**Issue by ankitatiisc** [chaneyddtt/Coarse-to-fine-3D-Animal#3]
Hi authors,
Is there some API to retrieve the 3D mesh in .ply and .obj format in your method ?

**Comment by chaneyddtt** [comment]
Hi @ankitatiisc,
We do not have an API for mesh retrieve, perhaps you can feed the image into our pretrained model to get the 3D mesh.

**Comment by ankitatiisc** [comment]
> 

@chaneyddtt Similar to your Visualizer.generate_output_figures_v2 function; is there function to directly save mesh in the .ply format ? Sorry for not asking this question directly earlier.

**Comment by chaneyddtt** [comment]
For visualization, you can use trimesh and pyrender, here is an example:
![image](https://user-images.githubusercontent.com/31334319/148538557-722635f7-5adf-45c7-9ca2-3c3b6f954f13.png)
Alternatively, you can also use the plotly.graph_objects to visualize the mesh. The export() function in Trimesh can be used to save mesh data.

**Comment by ankitatiisc** [comment]
Thanks!
