### ISSUE TITLE
Quesion about stage 2 results

### ISSUE THREAD

**Issue by MooreManor** [chaneyddtt/Coarse-to-fine-3D-Animal#7]
@chaneyddtt 

Do you still remember the results after stage2 which freezes the coarse network and only trains the subsequent network? Do the results get better before stage 3, or only after stage 3 the results get better?

**Comment by chaneyddtt** [comment]
Hi @MooreManor, the results in terms of keypoints PCK are slightly better after stage2, but not in terms of mask IOU. This is because we only apply keypoints supervision in stage1 and stage2. Both measures improve only after stage 3.

**Comment by MooreManor** [comment]
@chaneyddtt 

Thanks! By the way, did you try to optimize the camera parameters in stage 2 and 3?

**Comment by chaneyddtt** [comment]
Not in stage 2 since the coarse estimation part is frozen, but yes in stage 3 since the whole network is optimized.

**Comment by MooreManor** [comment]
:) clear now! Thanks for your quick reply!!!
